[package]
name = "enterprise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloud-api = { path = "../dfs/cloud-api" }
tokio.workspace = true